default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: valtari 
  host: localhost
  port: 5432

test:
  <<: *default
  database: valtari_test 

production:
  <<: *default
