=begin
Revenue.create(name: "< 1M")
Revenue.create(name: "1 - 2M")
Revenue.create(name: "2 - 5M")
Revenue.create(name: "5 - 10M")
Revenue.create(name: "10 - 20M")
Revenue.create(name: "20 - 50M")
Revenue.create(name: "50 - 100M")
Revenue.create(name: "100 - 200M")
Revenue.create(name: "200 - 500M")
Revenue.create(name: "500 - 1B")

Ebidtum.create(name: "< 1M")
Ebidtum.create(name: "1 - 2M")
Ebidtum.create(name: "2 - 5M")
Ebidtum.create(name: "5 - 10M")
Ebidtum.create(name: "10 - 20M")
Ebidtum.create(name: "20 - 50M")
Ebidtum.create(name: "50 - 100M")
Ebidtum.create(name: "100 - 200M")
Ebidtum.create(name: "200 - 500M")
Ebidtum.create(name: "500 - 1B")

Industry.create!(code: '111110', name: 'Soybean Farming')
Industry.create!(code: '111120', name: 'Oilseed (except Soybean) Farming')
Industry.create!(code: '111130', name: 'Dry Pea and Bean Farming')
Industry.create!(code: '111140', name: 'Wheat Farming')
Industry.create!(code: '111150', name: 'Corn Farming')
Industry.create!(code: '111160', name: 'Rice Farming')
Industry.create!(code: '111191', name: 'Oilseed and Grain Combination Farming')
Industry.create!(code: '111199', name: 'All Other Grain Farming')
Industry.create!(code: '111211', name: 'Potato Farming')
Industry.create!(code: '111219', name: 'Other Vegetable (except Potato) and Melon Farming')
Industry.create!(code: '111310', name: 'Orange Groves')
Industry.create!(code: '111320', name:'Citrus (except Orange) Groves')
Industry.create!(code: '111331', name: 'Apple Orchardsk')
=end
CompanyType.create!( category: 'Capital Providers', name: 'Private Equity Group')
CompanyType.create!( category: 'Capital Providers', name: 'Family Office')
CompanyType.create!( category: 'Capital Providers', name: 'Senior Lender')
CompanyType.create!( category: 'Capital Providers', name: 'Junior Capital Provider')
CompanyType.create!( category: 'Capital Providers', name: 'Individual Accredited Investor')
CompanyType.create!( category: 'Capital Providers', name: 'Venture Capital')
CompanyType.create!( category: 'Capital Providers', name: 'Search Fund')
CompanyType.create!( category: 'Capital Providers', name: 'Independent Sponsor')
CompanyType.create!( category: 'Capital Providers', name: 'Hedge Fund')
CompanyType.create!( category: 'Capital Providers', name: 'Holding Company')
CompanyType.create!( category: 'Capital Providers', name: 'Sovereign Wealth')
CompanyType.create!( category: 'Advisor', name: 'Merchant Bank')
CompanyType.create!( category: 'Advisor', name: 'Investor Bank')
CompanyType.create!( category: 'Advisor', name: 'M&A Advisory Firm')
CompanyType.create!( category: 'Advisor', name: 'Business Broker')
CompanyType.create!( category: 'Advisor', name: 'Consultant')
CompanyType.create!( category: 'Advisor', name: 'Law Firm')
CompanyType.create!( category: 'Advisor', name: 'Accountant')
CompanyType.create!( category: 'Company Owners & Strategics', name: 'Corporation')
